version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: api-bank-account
    restart: always
    image: node:12
    working_dir: /usr/src/bank-account-api
    command: bash -c "npm install --only=prod && npm run debug"
    volumes: 
      - ./dist/:/usr/src/bank-account-api/dist
      - ./package.json:/usr/src/bank-account-api/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"      
    links:
      - mongo
    environment: 
      - MONGO_URL=mongodb://mongo:27017/bank-account