version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  checklint:
    executor: docker-image
    steps:
        - checkout
        - node/install-packages:
            cache-path: ~/project/node_modules
            override-ci-command: npm install
        - run:
            command: eslint 'src/**'