version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:coveralls
workflows:
  version: 2
  build:
    jobs:
      - lint
      - test